version: '3.8'

services:
  blue:
    build:
      context: ./app/blue-app
    container_name: blue

  green:
    build:
      context: ./app/green-app
    container_name: green

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - blue
      - green

volumes:
  state:
