version: '3'
services:
  blue:
    build:
      context: ./app/blue-app
    container_name: blue

  green:
    build:
      context: ./app/green-app
    container_name: green

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - blue
      - green
